title: "شريف محمد جابر"
description: "أرشيف فكري منظم للكاتب شريف محمد جابر"
lang: ar
markdown: kramdown
theme: minima
permalink: pretty
collections:
  posts:
    output: true
    permalink: /:categories/:title/
plugins:
  - jekyll-feed
  - jekyll-seo-tag
